import type { AdminNavGroup, EntityConfigMap } from "./shared";
import {
  productAttributeDataTypes,
  productLookup,
  productStatuses,
  productTypes,
  supplierLookup,
  unitLookup,
} from "./shared";

export const catalogConfigs = {
  product_categories: {
    title: "Product categories",
    apiPath: "/api/product-categories",
    fields: [
      { key: "name", label: "Name", kind: "text", required: true },
      { key: "code", label: "Code", kind: "text", required: true },
      { key: "parent_category_id", label: "Parent category ID", kind: "number" },
      { key: "description", label: "Description", kind: "textarea" },
      { key: "is_active", label: "Active", kind: "checkbox", defaultChecked: true },
    ],
  },
  units: {
    title: "Units",
    apiPath: "/api/units",
    fields: [
      { key: "name", label: "Name", kind: "text", required: true },
      { key: "code", label: "Code", kind: "text", required: true },
      { key: "symbol", label: "Symbol", kind: "text" },
      { key: "description", label: "Description", kind: "textarea" },
      { key: "is_active", label: "Active", kind: "checkbox", defaultChecked: true },
    ],
  },
  suppliers: {
    title: "Suppliers",
    apiPath: "/api/suppliers",
    fields: [
      { key: "name", label: "Name", kind: "text", required: true },
      { key: "code", label: "Code", kind: "text", required: true },
      { key: "contact_person", label: "Contact person", kind: "text" },
      { key: "phone", label: "Phone", kind: "text" },
      { key: "email", label: "Email", kind: "text" },
      { key: "address_text", label: "Address", kind: "textarea" },
      { key: "city", label: "City", kind: "text" },
      { key: "country", label: "Country", kind: "text" },
      { key: "tax_id", label: "Tax ID", kind: "text" },
      { key: "notes", label: "Notes", kind: "textarea" },
      { key: "is_active", label: "Active", kind: "checkbox", defaultChecked: true },
    ],
  },
  products: {
    title: "Products",
    apiPath: "/api/products",
    tableColumns: [
      { key: "name", label: "Product" },
      { key: "sku", label: "SKU" },
      { key: "product_type", label: "Type", format: "status" },
      { key: "status", label: "Status", format: "status" },
      { key: "brand", label: "Brand" },
      { key: "minimum_sale_price", label: "Min Sale Price", format: "money" },
    ],
    searchKeys: ["name", "sku", "code", "brand"],
    filters: [
      { key: "product_type", label: "Product type", options: productTypes },
      { key: "status", label: "Status", options: productStatuses },
    ],
    formSections: [
      { key: "core", label: "Core Info" },
      { key: "classification", label: "Classification" },
      { key: "pricing", label: "Pricing / Status" },
      { key: "defaults", label: "Defaults / Notes" },
    ],
    fields: [
      { key: "name", label: "Name", kind: "text", required: true, section: "core" },
      { key: "sku", label: "SKU", kind: "text", required: true, section: "core" },
      { key: "barcode", label: "Barcode", kind: "text", section: "core" },
      { key: "brand", label: "Brand", kind: "text", section: "core" },
      { key: "category_id", label: "Category ID", kind: "number", section: "classification" },
      { key: "product_type", label: "Product type", kind: "select", required: true, options: productTypes, section: "classification" },
      { key: "has_variants", label: "Has variants", kind: "checkbox", section: "classification" },
      { key: "has_attributes", label: "Has attributes", kind: "checkbox", section: "classification" },
      { key: "minimum_sale_price", label: "Minimum sale price", kind: "number", step: "any", section: "pricing" },
      { key: "status", label: "Status", kind: "select", options: productStatuses, section: "pricing" },
      { key: "is_stock_tracked", label: "Stock tracked", kind: "checkbox", defaultChecked: true, section: "pricing" },
      { key: "is_sellable", label: "Sellable", kind: "checkbox", defaultChecked: true, section: "pricing" },
      { key: "is_purchasable", label: "Purchasable", kind: "checkbox", defaultChecked: true, section: "pricing" },
      { key: "is_service", label: "Service", kind: "checkbox", section: "pricing" },
      { key: "default_unit_id", label: "Default unit", kind: "select", required: true, lookup: unitLookup, section: "defaults" },
      { key: "allow_manual_price", label: "Allow manual price", kind: "checkbox", section: "defaults" },
      { key: "description", label: "Description", kind: "textarea", section: "defaults" },
      { key: "short_description", label: "Short description", kind: "textarea", section: "defaults" },
    ],
  },
  product_attributes: {
    title: "Product attributes",
    apiPath: "/api/product-attributes",
    fields: [
      { key: "name", label: "Name", kind: "text", required: true },
      { key: "code", label: "Code", kind: "text", required: true },
      { key: "data_type", label: "Data type", kind: "select", required: true, options: productAttributeDataTypes },
      { key: "unit_hint", label: "Unit hint", kind: "text" },
      { key: "is_filterable", label: "Filterable", kind: "checkbox" },
      { key: "is_required", label: "Required", kind: "checkbox" },
      { key: "is_active", label: "Active", kind: "checkbox", defaultChecked: true },
    ],
  },
  product_attribute_values: {
    title: "Product attribute values",
    apiPath: "/api/product-attribute-values",
    fields: [
      { key: "product_id", label: "Product", kind: "select", required: true, lookup: productLookup },
      { key: "attribute_id", label: "Attribute ID", kind: "number", required: true },
      { key: "value_text", label: "Value text", kind: "text" },
      { key: "value_number", label: "Value number", kind: "number", step: "any" },
      { key: "value_boolean", label: "Value boolean", kind: "boolean-select" },
      { key: "value_json", label: "Value JSON", kind: "textarea" },
    ],
  },
  product_suppliers: {
    title: "Product suppliers",
    apiPath: "/api/product-suppliers",
    fields: [
      { key: "product_id", label: "Product", kind: "select", required: true, lookup: productLookup },
      { key: "supplier_id", label: "Supplier", kind: "select", required: true, lookup: supplierLookup },
      { key: "supplier_sku", label: "Supplier SKU", kind: "text" },
      { key: "purchase_price", label: "Purchase price", kind: "number", step: "any" },
      { key: "currency", label: "Currency", kind: "text" },
      { key: "lead_time_days", label: "Lead time days", kind: "number", min: 0 },
      { key: "is_preferred", label: "Preferred", kind: "checkbox" },
    ],
  },
  product_bundles: {
    title: "Product bundles",
    apiPath: "/api/product-bundles",
    fields: [
      { key: "bundle_product_id", label: "Bundle product", kind: "select", required: true, lookup: productLookup },
      { key: "name", label: "Name", kind: "text", required: true },
      { key: "code", label: "Code", kind: "text", required: true },
      { key: "description", label: "Description", kind: "textarea" },
      { key: "is_active", label: "Active", kind: "checkbox", defaultChecked: true },
    ],
  },
  product_bundle_items: {
    title: "Product bundle items",
    apiPath: "/api/product-bundle-items",
    fields: [
      { key: "bundle_id", label: "Bundle ID", kind: "number", required: true },
      { key: "component_product_id", label: "Component product", kind: "select", required: true, lookup: productLookup },
      { key: "quantity", label: "Quantity", kind: "number", required: true, min: 0.000001, step: "any" },
      { key: "unit_id", label: "Unit", kind: "select", required: true, lookup: unitLookup },
      { key: "sort_order", label: "Sort order", kind: "number", min: 0 },
      { key: "is_optional", label: "Optional", kind: "checkbox" },
    ],
  },
} as const satisfies EntityConfigMap;

export const catalogNavGroup: AdminNavGroup = {
  label: "Catalog",
  href: "/admin/catalog",
  items: [
    { href: "/admin/products", label: "Products" },
    { href: "/admin/product-categories", label: "Product Categories" },
    { href: "/admin/units", label: "Units" },
    { href: "/admin/suppliers", label: "Suppliers" },
    { href: "/admin/product-attributes", label: "Product Attributes" },
    { href: "/admin/product-attribute-values", label: "Product Attribute Values" },
    { href: "/admin/product-suppliers", label: "Product Suppliers" },
    { href: "/admin/product-bundles", label: "Product Bundles" },
    { href: "/admin/product-bundle-items", label: "Product Bundle Items" },
  ],
};
