import type { AdminNavGroup, EntityConfigMap } from "./shared";
import {
  commercialLineTypes,
  commercialReservationStatuses,
  discountTypes,
  fulfillmentStatuses,
  fulfillmentTypes,
  orderLookup,
  orderPaymentStatuses,
  orderStatuses,
  paymentMethodLookup,
  paymentRecordStatuses,
  productLookup,
  quoteLookup,
  quoteStatuses,
  quoteVersionLookup,
  quoteVersionStatuses,
  unitLookup,
  userLookup,
  variantLookup,
} from "./shared";

export const commercialConfigs = {
  quotes: {
    title: "Quotes",
    apiPath: "/api/quotes",
    fields: [
      { key: "deal_id", label: "Deal ID", kind: "number" },
      { key: "quote_number", label: "Quote number", kind: "text", required: true },
      { key: "status", label: "Status", kind: "select", options: quoteStatuses },
      { key: "currency", label: "Currency", kind: "text" },
      { key: "minimum_sale_total", label: "Minimum sale total", kind: "number", step: "any", min: 0 },
      { key: "actual_sale_total", label: "Actual sale total", kind: "number", step: "any", min: 0 },
      { key: "discount_total", label: "Discount total", kind: "number", step: "any", min: 0 },
      { key: "grand_total", label: "Grand total", kind: "number", step: "any", min: 0 },
      { key: "valid_until", label: "Valid until", kind: "date" },
      { key: "created_by_user_id", label: "Created by user", kind: "select", lookup: userLookup },
      { key: "approved_by_user_id", label: "Approved by user", kind: "select", lookup: userLookup },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  quote_versions: {
    title: "Quote versions",
    apiPath: "/api/quote-versions",
    listNotice: {
      title: "Only untouched drafts can be deleted",
      description:
        "Use the quote-version workflow page to remove a true draft before it has linked orders, reservations, documents, or follow-through history.",
      tone: "warning",
    },
    detailBasePath: "/admin/quote-versions",
    detailLabelKey: "version_number",
    tableColumns: [
      { key: "quote_id", label: "Quote" },
      { key: "version_number", label: "Version" },
      { key: "version_status", label: "Status", format: "status" },
      { key: "reservation_status", label: "Reservation", format: "status" },
      { key: "actual_sale_total", label: "Actual Total", format: "money" },
      { key: "grand_total", label: "Grand Total", format: "money" },
    ],
    searchKeys: ["version_number", "quote_id", "notes"],
    filters: [
      { key: "version_status", label: "Version status", options: quoteVersionStatuses },
    ],
    formSections: [
      { key: "core", label: "Core Info" },
      { key: "status", label: "Status & Validity" },
      { key: "totals", label: "Totals" },
      { key: "notes", label: "Notes" },
    ],
    fields: [
      { key: "quote_id", label: "Quote", kind: "select", required: true, lookup: quoteLookup, section: "core" },
      { key: "version_number", label: "Version number", kind: "number", required: true, section: "core" },
      { key: "based_on_version_id", label: "Based on version", kind: "select", lookup: quoteVersionLookup, section: "core" },
      { key: "created_by_user_id", label: "Created by user", kind: "select", lookup: userLookup, section: "core" },
      { key: "version_status", label: "Version status", kind: "select", options: quoteVersionStatuses, section: "status" },
      { key: "reservation_status", label: "Reservation status", kind: "select", options: commercialReservationStatuses, section: "status" },
      { key: "is_current", label: "Current", kind: "checkbox", defaultChecked: true, section: "status" },
      { key: "minimum_sale_total", label: "Minimum sale total", kind: "number", step: "any", min: 0, section: "totals" },
      { key: "actual_sale_total", label: "Actual sale total", kind: "number", step: "any", min: 0, section: "totals" },
      { key: "discount_total", label: "Discount total", kind: "number", step: "any", min: 0, section: "totals" },
      { key: "grand_total", label: "Grand total", kind: "number", step: "any", min: 0, section: "totals" },
      { key: "notes", label: "Notes", kind: "textarea", section: "notes" },
    ],
  },
  quote_lines: {
    title: "Quote lines",
    apiPath: "/api/quote-lines",
    fields: [
      { key: "quote_version_id", label: "Quote version", kind: "select", required: true, lookup: quoteVersionLookup },
      { key: "line_number", label: "Line number", kind: "number", required: true },
      { key: "line_type", label: "Line type", kind: "select", required: true, options: commercialLineTypes },
      { key: "product_id", label: "Product", kind: "select", lookup: productLookup },
      { key: "configuration_variant_id", label: "Configuration variant", kind: "select", lookup: variantLookup },
      { key: "quantity", label: "Quantity", kind: "number", required: true, step: "any", min: 0.000001 },
      { key: "unit_id", label: "Unit", kind: "select", required: true, lookup: unitLookup },
      { key: "unit_price", label: "Unit price", kind: "number", step: "any", min: 0 },
      { key: "minimum_unit_price", label: "Minimum unit price", kind: "number", step: "any", min: 0 },
      { key: "line_discount_type", label: "Line discount type", kind: "select", options: discountTypes },
      { key: "line_discount_value", label: "Line discount value", kind: "number", step: "any", min: 0 },
      { key: "line_discount_total", label: "Line discount total", kind: "number", step: "any", min: 0 },
      { key: "line_total", label: "Line total", kind: "number", step: "any", min: 0 },
      { key: "snapshot_product_name", label: "Snapshot product name", kind: "text", required: true },
      { key: "snapshot_sku", label: "Snapshot SKU", kind: "text", required: true },
      { key: "snapshot_unit_name", label: "Snapshot unit name", kind: "text", required: true },
      { key: "snapshot_description", label: "Snapshot description", kind: "textarea" },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  quote_discounts: {
    title: "Quote discounts",
    apiPath: "/api/quote-discounts",
    fields: [
      { key: "quote_version_id", label: "Quote version", kind: "select", required: true, lookup: quoteVersionLookup },
      { key: "discount_type", label: "Discount type", kind: "select", required: true, options: discountTypes },
      { key: "discount_value", label: "Discount value", kind: "number", required: true, step: "any", min: 0 },
      { key: "discount_total", label: "Discount total", kind: "number", step: "any", min: 0 },
      { key: "reason", label: "Reason", kind: "textarea" },
      { key: "created_by_user_id", label: "Created by user", kind: "select", lookup: userLookup },
    ],
  },
  orders: {
    title: "Orders",
    apiPath: "/api/orders",
    detailBasePath: "/admin/orders",
    detailLabelKey: "order_number",
    tableColumns: [
      { key: "order_number", label: "Order" },
      { key: "order_status", label: "Order Status", format: "status" },
      { key: "payment_status", label: "Payment", format: "status" },
      { key: "reservation_status", label: "Reservation", format: "status" },
      { key: "grand_total", label: "Grand Total", format: "money" },
      { key: "remaining_total", label: "Remaining", format: "money" },
      { key: "order_date", label: "Order Date", format: "date" },
    ],
    searchKeys: ["order_number", "notes"],
    filters: [
      { key: "order_status", label: "Order status", options: orderStatuses },
      { key: "payment_status", label: "Payment status", options: orderPaymentStatuses },
    ],
    formSections: [
      { key: "core", label: "Core Info" },
      { key: "status", label: "Status & Dates" },
      { key: "financials", label: "Financials" },
      { key: "notes", label: "Notes / Context" },
    ],
    fields: [
      { key: "quote_version_id", label: "Quote version", kind: "select", lookup: quoteVersionLookup, section: "core" },
      { key: "customer_id", label: "Customer ID", kind: "number", section: "core" },
      { key: "deal_id", label: "Deal ID", kind: "number", section: "core" },
      { key: "order_number", label: "Order number", kind: "text", required: true, section: "core" },
      { key: "currency", label: "Currency", kind: "text", section: "core" },
      { key: "installation_required", label: "Installation required", kind: "checkbox", section: "status" },
      { key: "fulfillment_type", label: "Fulfillment type", kind: "select", options: fulfillmentTypes, section: "status" },
      { key: "order_status", label: "Order status", kind: "select", options: orderStatuses, section: "status" },
      { key: "payment_status", label: "Payment status", kind: "select", options: orderPaymentStatuses, section: "status" },
      { key: "reservation_status", label: "Reservation status", kind: "select", options: commercialReservationStatuses, section: "status" },
      { key: "order_date", label: "Order date", kind: "date", section: "status" },
      { key: "planned_installation_date", label: "Planned installation date", kind: "date", section: "status" },
      { key: "completed_at", label: "Completed at", kind: "datetime-local", section: "status" },
      { key: "minimum_sale_total", label: "Minimum sale total", kind: "number", step: "any", min: 0, section: "financials" },
      { key: "actual_sale_total", label: "Actual sale total", kind: "number", step: "any", min: 0, section: "financials" },
      { key: "discount_total", label: "Discount total", kind: "number", step: "any", min: 0, section: "financials" },
      { key: "grand_total", label: "Grand total", kind: "number", step: "any", min: 0, section: "financials" },
      { key: "paid_total", label: "Paid total", kind: "number", step: "any", min: 0, section: "financials" },
      { key: "remaining_total", label: "Remaining total", kind: "number", step: "any", min: 0, section: "financials" },
      { key: "created_by_user_id", label: "Created by user", kind: "select", lookup: userLookup, section: "notes" },
      { key: "approved_by_user_id", label: "Approved by user", kind: "select", lookup: userLookup, section: "notes" },
      { key: "notes", label: "Notes", kind: "textarea", section: "notes" },
    ],
  },
  order_lines: {
    title: "Order lines",
    apiPath: "/api/order-lines",
    fields: [
      { key: "order_id", label: "Order", kind: "select", required: true, lookup: orderLookup },
      { key: "line_number", label: "Line number", kind: "number", required: true },
      { key: "line_type", label: "Line type", kind: "select", required: true, options: commercialLineTypes },
      { key: "product_id", label: "Product", kind: "select", lookup: productLookup },
      { key: "configuration_variant_id", label: "Configuration variant", kind: "select", lookup: variantLookup },
      { key: "quantity", label: "Quantity", kind: "number", required: true, step: "any", min: 0.000001 },
      { key: "unit_id", label: "Unit", kind: "select", required: true, lookup: unitLookup },
      { key: "unit_price", label: "Unit price", kind: "number", step: "any", min: 0 },
      { key: "minimum_unit_price", label: "Minimum unit price", kind: "number", step: "any", min: 0 },
      { key: "line_discount_type", label: "Line discount type", kind: "select", options: discountTypes },
      { key: "line_discount_value", label: "Line discount value", kind: "number", step: "any", min: 0 },
      { key: "line_discount_total", label: "Line discount total", kind: "number", step: "any", min: 0 },
      { key: "line_total", label: "Line total", kind: "number", step: "any", min: 0 },
      { key: "fulfillment_status", label: "Fulfillment status", kind: "select", options: fulfillmentStatuses },
      { key: "snapshot_product_name", label: "Snapshot product name", kind: "text", required: true },
      { key: "snapshot_sku", label: "Snapshot SKU", kind: "text", required: true },
      { key: "snapshot_unit_name", label: "Snapshot unit name", kind: "text", required: true },
      { key: "snapshot_description", label: "Snapshot description", kind: "textarea" },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  order_discounts: {
    title: "Order discounts",
    apiPath: "/api/order-discounts",
    fields: [
      { key: "order_id", label: "Order", kind: "select", required: true, lookup: orderLookup },
      { key: "discount_type", label: "Discount type", kind: "select", required: true, options: discountTypes },
      { key: "discount_value", label: "Discount value", kind: "number", required: true, step: "any", min: 0 },
      { key: "discount_total", label: "Discount total", kind: "number", step: "any", min: 0 },
      { key: "reason", label: "Reason", kind: "textarea" },
      { key: "created_by_user_id", label: "Created by user", kind: "select", lookup: userLookup },
    ],
  },
  payment_methods: {
    title: "Payment methods",
    apiPath: "/api/payment-methods",
    fields: [
      { key: "name", label: "Name", kind: "text", required: true },
      { key: "code", label: "Code", kind: "text", required: true },
      { key: "description", label: "Description", kind: "textarea" },
      { key: "is_active", label: "Active", kind: "checkbox", defaultChecked: true },
    ],
  },
  payments: {
    title: "Payments",
    apiPath: "/api/payments",
    tableColumns: [
      { key: "order_id", label: "Order" },
      { key: "payment_method_id", label: "Method" },
      { key: "amount", label: "Amount", format: "money" },
      { key: "currency", label: "Currency" },
      { key: "status", label: "Status", format: "status" },
      { key: "payment_date", label: "Payment Date", format: "date" },
      { key: "reference_number", label: "Reference" },
    ],
    searchKeys: ["reference_number", "notes"],
    filters: [
      { key: "status", label: "Status", options: paymentRecordStatuses },
    ],
    formSections: [
      { key: "core", label: "Core Info" },
      { key: "payment", label: "Payment Details" },
      { key: "notes", label: "Notes / Context" },
    ],
    fields: [
      { key: "order_id", label: "Order", kind: "select", required: true, lookup: orderLookup, section: "core" },
      { key: "payment_method_id", label: "Payment method", kind: "select", required: true, lookup: paymentMethodLookup, section: "core" },
      { key: "payment_date", label: "Payment date", kind: "date", required: true, section: "payment" },
      { key: "amount", label: "Amount", kind: "number", required: true, step: "any", min: 0.000001, section: "payment" },
      { key: "currency", label: "Currency", kind: "text", section: "payment" },
      { key: "reference_number", label: "Reference number", kind: "text", section: "payment" },
      { key: "status", label: "Status", kind: "select", options: paymentRecordStatuses, section: "payment" },
      { key: "received_by_user_id", label: "Received by user", kind: "select", lookup: userLookup, section: "notes" },
      { key: "notes", label: "Notes", kind: "textarea", section: "notes" },
    ],
  },
} as const satisfies EntityConfigMap;

export const commercialNavGroup: AdminNavGroup = {
  label: "Commercial",
  href: "/admin/commercial",
  items: [
    { href: "/admin/quotes", label: "Quotes" },
    { href: "/admin/quote-versions", label: "Quote Versions" },
    { href: "/admin/orders", label: "Orders" },
    { href: "/admin/payments", label: "Payments" },
    { href: "/admin/payment-methods", label: "Payment Methods" },
    { href: "/admin/quote-lines", label: "Quote Lines" },
    { href: "/admin/quote-discounts", label: "Quote Discounts" },
    { href: "/admin/order-lines", label: "Order Lines" },
    { href: "/admin/order-discounts", label: "Order Discounts" },
  ],
};
