import type { AdminNavGroup, EntityConfigMap } from "./shared";
import {
  documentEntityTypes,
  documentGenerationStatuses,
  documentLinkRoles,
  documentOutputFormats,
  documentTemplateLookup,
  documentTemplateTypes,
  generatedDocumentLookup,
  userLookup,
} from "./shared";

export const documentConfigs = {
  document_templates: {
    title: "Document templates",
    apiPath: "/api/document-templates",
    formSections: [
      { key: "identity", label: "Template & Identity" },
      { key: "content", label: "Content & Scope" },
      { key: "status", label: "Status / Ownership" },
    ],
    fields: [
      { key: "name", label: "Name", kind: "text", required: true, section: "identity" },
      { key: "code", label: "Code", kind: "text", required: true, section: "identity" },
      { key: "template_type", label: "Template type", kind: "select", required: true, options: documentTemplateTypes, section: "identity" },
      { key: "entity_type", label: "Entity type", kind: "select", required: true, options: documentEntityTypes, section: "content" },
      { key: "output_format", label: "Output format", kind: "select", required: true, options: documentOutputFormats, section: "content" },
      { key: "description", label: "Description", kind: "textarea", section: "content" },
      { key: "template_content", label: "Template content", kind: "textarea", section: "content" },
      { key: "is_active", label: "Active", kind: "checkbox", defaultChecked: true, section: "status" },
      { key: "created_by_user_id", label: "Created by user", kind: "select", lookup: userLookup, section: "status" },
    ],
  },
  generated_documents: {
    title: "Generated documents",
    apiPath: "/api/generated-documents",
    detailBasePath: "/admin/generated-documents",
    detailLabelKey: "title",
    searchKeys: ["title", "document_number"],
    filters: [
      { key: "generation_status", label: "Generation status", options: documentGenerationStatuses },
      { key: "entity_type", label: "Entity type", options: documentEntityTypes },
    ],
    formSections: [
      { key: "identity", label: "Template & Identity" },
      { key: "binding", label: "Entity Binding" },
      { key: "output", label: "Output / File Info" },
    ],
    fields: [
      { key: "template_id", label: "Template", kind: "select", required: true, lookup: documentTemplateLookup, section: "identity" },
      { key: "document_number", label: "Document number", kind: "text", section: "identity" },
      { key: "title", label: "Title", kind: "text", required: true, section: "identity" },
      { key: "entity_type", label: "Entity type", kind: "select", required: true, options: documentEntityTypes, section: "binding" },
      { key: "entity_id", label: "Entity ID", kind: "number", required: true, section: "binding" },
      { key: "generation_status", label: "Generation status", kind: "select", options: documentGenerationStatuses, section: "output" },
      { key: "rendered_content", label: "Rendered content", kind: "textarea", section: "output" },
      { key: "file_url", label: "File URL", kind: "text", section: "output" },
      { key: "file_name", label: "File name", kind: "text", section: "output" },
      { key: "mime_type", label: "MIME type", kind: "text", section: "output" },
      { key: "generated_by_user_id", label: "Generated by user", kind: "select", lookup: userLookup, section: "output" },
      { key: "generated_at", label: "Generated at", kind: "datetime-local", section: "output" },
    ],
  },
  document_links: {
    title: "Document links",
    apiPath: "/api/document-links",
    fields: [
      { key: "generated_document_id", label: "Generated document", kind: "select", required: true, lookup: generatedDocumentLookup },
      { key: "entity_type", label: "Entity type", kind: "select", required: true, options: documentEntityTypes },
      { key: "entity_id", label: "Entity ID", kind: "number", required: true },
      { key: "link_role", label: "Link role", kind: "select", required: true, options: documentLinkRoles },
    ],
  },
} as const satisfies EntityConfigMap;

export const documentNavGroup: AdminNavGroup = {
  label: "Documents",
  href: "/admin/documents",
  items: [
    { href: "/admin/generated-documents", label: "Generated Documents" },
    { href: "/admin/document-templates", label: "Document Templates" },
    { href: "/admin/document-links", label: "Document Links" },
  ],
};
