import type { AdminNavGroup, EntityConfigMap } from "./shared";
import {
  documentEntityTypes,
  documentGenerationStatuses,
  documentLinkRoles,
  documentOutputFormats,
  documentTemplateLookup,
  documentTemplateTypes,
  generatedDocumentLookup,
  userLookup,
} from "./shared";

export const documentConfigs = {
  document_templates: {
    title: "Document templates",
    apiPath: "/api/document-templates",
    fields: [
      { key: "name", label: "Name", kind: "text", required: true },
      { key: "code", label: "Code", kind: "text", required: true },
      { key: "template_type", label: "Template type", kind: "select", required: true, options: documentTemplateTypes },
      { key: "entity_type", label: "Entity type", kind: "select", required: true, options: documentEntityTypes },
      { key: "description", label: "Description", kind: "textarea" },
      { key: "template_content", label: "Template content", kind: "textarea" },
      { key: "output_format", label: "Output format", kind: "select", required: true, options: documentOutputFormats },
      { key: "is_active", label: "Active", kind: "checkbox", defaultChecked: true },
      { key: "created_by_user_id", label: "Created by user", kind: "select", lookup: userLookup },
    ],
  },
  generated_documents: {
    title: "Generated documents",
    apiPath: "/api/generated-documents",
    fields: [
      { key: "template_id", label: "Template", kind: "select", required: true, lookup: documentTemplateLookup },
      { key: "document_number", label: "Document number", kind: "text" },
      { key: "title", label: "Title", kind: "text", required: true },
      { key: "entity_type", label: "Entity type", kind: "select", required: true, options: documentEntityTypes },
      { key: "entity_id", label: "Entity ID", kind: "number", required: true },
      { key: "generation_status", label: "Generation status", kind: "select", options: documentGenerationStatuses },
      { key: "rendered_content", label: "Rendered content", kind: "textarea" },
      { key: "file_url", label: "File URL", kind: "text" },
      { key: "file_name", label: "File name", kind: "text" },
      { key: "mime_type", label: "MIME type", kind: "text" },
      { key: "generated_by_user_id", label: "Generated by user", kind: "select", lookup: userLookup },
      { key: "generated_at", label: "Generated at", kind: "datetime-local" },
    ],
  },
  document_links: {
    title: "Document links",
    apiPath: "/api/document-links",
    fields: [
      { key: "generated_document_id", label: "Generated document", kind: "select", required: true, lookup: generatedDocumentLookup },
      { key: "entity_type", label: "Entity type", kind: "select", required: true, options: documentEntityTypes },
      { key: "entity_id", label: "Entity ID", kind: "number", required: true },
      { key: "link_role", label: "Link role", kind: "select", required: true, options: documentLinkRoles },
    ],
  },
} as const satisfies EntityConfigMap;

export const documentNavGroup: AdminNavGroup = {
  label: "Documents",
  items: [
    { href: "/admin/document-templates", label: "Document Templates" },
    { href: "/admin/generated-documents", label: "Generated Documents" },
    { href: "/admin/document-links", label: "Document Links" },
  ],
};
