import type { AdminNavGroup, EntityConfigMap } from "./shared";
import {
  inventoryCountStatuses,
  orderLineLookup,
  positionTypes,
  productLookup,
  quoteLineLookup,
  reservationStatuses,
  stockMovementLookup,
  stockMovementStatuses,
  stockMovementTypes,
  unitLookup,
  userLookup,
  variantLookup,
  warehouseDocumentStatuses,
  warehouseLookup,
  warehousePositionLookup,
  warehouseTypes,
  writeoffReasons,
} from "./shared";

export const warehouseConfigs = {
  warehouses: {
    title: "Warehouses",
    apiPath: "/api/warehouses",
    fields: [
      { key: "location_id", label: "Location ID", kind: "number", required: true },
      { key: "name", label: "Name", kind: "text", required: true },
      { key: "code", label: "Code", kind: "text", required: true },
      { key: "warehouse_type", label: "Warehouse type", kind: "select", required: true, options: warehouseTypes },
      { key: "is_external", label: "External", kind: "checkbox" },
      { key: "is_active", label: "Active", kind: "checkbox", defaultChecked: true },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  warehouse_positions: {
    title: "Warehouse positions",
    apiPath: "/api/warehouse-positions",
    fields: [
      { key: "warehouse_id", label: "Warehouse", kind: "select", required: true, lookup: warehouseLookup },
      { key: "name", label: "Name", kind: "text", required: true },
      { key: "code", label: "Code", kind: "text", required: true },
      { key: "position_type", label: "Position type", kind: "select", required: true, options: positionTypes },
      { key: "parent_position_id", label: "Parent position", kind: "select", lookup: warehousePositionLookup },
      { key: "sort_order", label: "Sort order", kind: "number" },
      { key: "is_active", label: "Active", kind: "checkbox", defaultChecked: true },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  stock_balances: {
    title: "Stock balances",
    apiPath: "/api/stock-balances",
    createEnabled: false,
    fields: [
      { key: "product_id", label: "Product", kind: "select", required: true, lookup: productLookup },
      { key: "warehouse_id", label: "Warehouse", kind: "select", required: true, lookup: warehouseLookup },
      { key: "position_id", label: "Position", kind: "select", required: true, lookup: warehousePositionLookup },
      { key: "on_hand_qty", label: "On hand qty", kind: "number", required: true, step: "any", min: 0 },
      { key: "reserved_qty", label: "Reserved qty", kind: "number", required: true, step: "any", min: 0 },
      { key: "available_qty", label: "Available qty", kind: "number", required: true, step: "any", min: 0 },
      { key: "last_recalculated_at", label: "Last recalculated at", kind: "datetime-local" },
    ],
  },
  stock_movements: {
    title: "Stock movements",
    apiPath: "/api/stock-movements",
    tableColumns: [
      { key: "reference_code", label: "Reference" },
      { key: "movement_type", label: "Movement Type", format: "status" },
      { key: "status", label: "Status", format: "status" },
      { key: "warehouse_id", label: "Warehouse" },
      { key: "source_warehouse_id", label: "Source" },
      { key: "destination_warehouse_id", label: "Destination" },
      { key: "movement_date", label: "Movement Date", format: "datetime" },
    ],
    searchKeys: ["reference_code", "related_entity_type", "related_entity_id", "notes"],
    filters: [
      { key: "movement_type", label: "Movement type", options: stockMovementTypes },
      { key: "status", label: "Status", options: stockMovementStatuses },
    ],
    formSections: [
      { key: "core", label: "Core Info" },
      { key: "warehouses", label: "Warehouse Context" },
      { key: "status", label: "Status & Timing" },
      { key: "notes", label: "Notes / Context" },
    ],
    fields: [
      { key: "movement_type", label: "Movement type", kind: "select", required: true, options: stockMovementTypes, section: "core" },
      { key: "reference_code", label: "Reference code", kind: "text", section: "core" },
      { key: "related_entity_type", label: "Related entity type", kind: "text", section: "core" },
      { key: "related_entity_id", label: "Related entity ID", kind: "text", section: "core" },
      { key: "warehouse_id", label: "Warehouse", kind: "select", lookup: warehouseLookup, section: "warehouses" },
      { key: "source_warehouse_id", label: "Source warehouse", kind: "select", lookup: warehouseLookup, section: "warehouses" },
      { key: "destination_warehouse_id", label: "Destination warehouse", kind: "select", lookup: warehouseLookup, section: "warehouses" },
      { key: "status", label: "Status", kind: "select", options: stockMovementStatuses, section: "status" },
      { key: "movement_date", label: "Movement date", kind: "datetime-local", required: true, section: "status" },
      { key: "performed_by_user_id", label: "Performed by user", kind: "select", lookup: userLookup, section: "notes" },
      { key: "approved_by_user_id", label: "Approved by user", kind: "select", lookup: userLookup, section: "notes" },
      { key: "notes", label: "Notes", kind: "textarea", section: "notes" },
    ],
  },
  stock_movement_lines: {
    title: "Stock movement lines",
    apiPath: "/api/stock-movement-lines",
    fields: [
      { key: "stock_movement_id", label: "Stock movement", kind: "select", required: true, lookup: stockMovementLookup },
      { key: "product_id", label: "Product", kind: "select", required: true, lookup: productLookup },
      { key: "from_position_id", label: "From position", kind: "select", lookup: warehousePositionLookup },
      { key: "to_position_id", label: "To position", kind: "select", lookup: warehousePositionLookup },
      { key: "quantity", label: "Quantity", kind: "number", required: true, step: "any", min: 0.000001 },
      { key: "unit_id", label: "Unit", kind: "select", required: true, lookup: unitLookup },
      { key: "unit_cost", label: "Unit cost", kind: "number", step: "any" },
      { key: "line_notes", label: "Line notes", kind: "textarea" },
    ],
  },
  purchase_receipts: {
    title: "Purchase receipts",
    apiPath: "/api/purchase-receipts",
    fields: [
      { key: "supplier_id", label: "Supplier ID", kind: "number", required: true },
      { key: "destination_warehouse_id", label: "Destination warehouse", kind: "select", required: true, lookup: warehouseLookup },
      { key: "receipt_date", label: "Receipt date", kind: "date", required: true },
      { key: "status", label: "Status", kind: "select", options: warehouseDocumentStatuses },
      { key: "receipt_number", label: "Receipt number", kind: "text" },
      { key: "source_document_number", label: "Source document number", kind: "text" },
      { key: "currency", label: "Currency", kind: "text" },
      { key: "total_amount", label: "Total amount", kind: "number", step: "any", min: 0 },
      { key: "received_by_user_id", label: "Received by user", kind: "select", lookup: userLookup },
      { key: "approved_by_user_id", label: "Approved by user", kind: "select", lookup: userLookup },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  purchase_receipt_lines: {
    title: "Purchase receipt lines",
    apiPath: "/api/purchase-receipt-lines",
    fields: [
      { key: "purchase_receipt_id", label: "Purchase receipt ID", kind: "number", required: true },
      { key: "line_number", label: "Line number", kind: "number", required: true },
      { key: "product_id", label: "Product", kind: "select", required: true, lookup: productLookup },
      { key: "destination_position_id", label: "Destination position", kind: "select", required: true, lookup: warehousePositionLookup },
      { key: "quantity", label: "Quantity", kind: "number", required: true, step: "any", min: 0.000001 },
      { key: "unit_id", label: "Unit", kind: "select", required: true, lookup: unitLookup },
      { key: "unit_cost", label: "Unit cost", kind: "number", step: "any", min: 0 },
      { key: "line_total", label: "Line total", kind: "number", step: "any", min: 0 },
      { key: "snapshot_product_name", label: "Snapshot product name", kind: "text", required: true },
      { key: "snapshot_sku", label: "Snapshot SKU", kind: "text", required: true },
      { key: "snapshot_unit_name", label: "Snapshot unit name", kind: "text", required: true },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  stock_adjustments: {
    title: "Stock adjustments",
    apiPath: "/api/stock-adjustments",
    fields: [
      { key: "warehouse_id", label: "Warehouse", kind: "select", required: true, lookup: warehouseLookup },
      { key: "adjustment_date", label: "Adjustment date", kind: "date", required: true },
      { key: "reason", label: "Reason", kind: "text" },
      { key: "status", label: "Status", kind: "select", options: warehouseDocumentStatuses },
      { key: "reference_code", label: "Reference code", kind: "text" },
      { key: "performed_by_user_id", label: "Performed by user", kind: "select", lookup: userLookup },
      { key: "approved_by_user_id", label: "Approved by user", kind: "select", lookup: userLookup },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  stock_adjustment_lines: {
    title: "Stock adjustment lines",
    apiPath: "/api/stock-adjustment-lines",
    fields: [
      { key: "stock_adjustment_id", label: "Stock adjustment ID", kind: "number", required: true },
      { key: "product_id", label: "Product", kind: "select", required: true, lookup: productLookup },
      { key: "position_id", label: "Position", kind: "select", required: true, lookup: warehousePositionLookup },
      { key: "old_qty", label: "Old qty", kind: "number", required: true, step: "any", min: 0 },
      { key: "new_qty", label: "New qty", kind: "number", required: true, step: "any", min: 0 },
      { key: "difference_qty", label: "Difference qty", kind: "number", required: true, step: "any" },
      { key: "unit_id", label: "Unit", kind: "select", required: true, lookup: unitLookup },
      { key: "line_notes", label: "Line notes", kind: "textarea" },
    ],
  },
  stock_writeoffs: {
    title: "Stock writeoffs",
    apiPath: "/api/stock-writeoffs",
    fields: [
      { key: "warehouse_id", label: "Warehouse", kind: "select", required: true, lookup: warehouseLookup },
      { key: "writeoff_date", label: "Writeoff date", kind: "date", required: true },
      { key: "writeoff_reason", label: "Writeoff reason", kind: "select", required: true, options: writeoffReasons },
      { key: "status", label: "Status", kind: "select", options: warehouseDocumentStatuses },
      { key: "reference_code", label: "Reference code", kind: "text" },
      { key: "performed_by_user_id", label: "Performed by user", kind: "select", lookup: userLookup },
      { key: "approved_by_user_id", label: "Approved by user", kind: "select", lookup: userLookup },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  stock_writeoff_lines: {
    title: "Stock writeoff lines",
    apiPath: "/api/stock-writeoff-lines",
    fields: [
      { key: "stock_writeoff_id", label: "Stock writeoff ID", kind: "number", required: true },
      { key: "product_id", label: "Product", kind: "select", required: true, lookup: productLookup },
      { key: "position_id", label: "Position", kind: "select", required: true, lookup: warehousePositionLookup },
      { key: "quantity", label: "Quantity", kind: "number", required: true, step: "any", min: 0.000001 },
      { key: "unit_id", label: "Unit", kind: "select", required: true, lookup: unitLookup },
      { key: "line_notes", label: "Line notes", kind: "textarea" },
    ],
  },
  inventory_counts: {
    title: "Inventory counts",
    apiPath: "/api/inventory-counts",
    fields: [
      { key: "warehouse_id", label: "Warehouse", kind: "select", required: true, lookup: warehouseLookup },
      { key: "count_date", label: "Count date", kind: "date", required: true },
      { key: "status", label: "Status", kind: "select", options: inventoryCountStatuses },
      { key: "reference_code", label: "Reference code", kind: "text" },
      { key: "performed_by_user_id", label: "Performed by user", kind: "select", lookup: userLookup },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  inventory_count_lines: {
    title: "Inventory count lines",
    apiPath: "/api/inventory-count-lines",
    fields: [
      { key: "inventory_count_id", label: "Inventory count ID", kind: "number", required: true },
      { key: "product_id", label: "Product", kind: "select", required: true, lookup: productLookup },
      { key: "position_id", label: "Position", kind: "select", required: true, lookup: warehousePositionLookup },
      { key: "system_qty", label: "System qty", kind: "number", required: true, step: "any", min: 0 },
      { key: "counted_qty", label: "Counted qty", kind: "number", required: true, step: "any", min: 0 },
      { key: "difference_qty", label: "Difference qty", kind: "number", required: true, step: "any" },
      { key: "unit_id", label: "Unit", kind: "select", required: true, lookup: unitLookup },
      { key: "line_notes", label: "Line notes", kind: "textarea" },
    ],
  },
  stock_transfer_documents: {
    title: "Stock transfer documents",
    apiPath: "/api/stock-transfer-documents",
    fields: [
      { key: "source_warehouse_id", label: "Source warehouse", kind: "select", required: true, lookup: warehouseLookup },
      { key: "destination_warehouse_id", label: "Destination warehouse", kind: "select", required: true, lookup: warehouseLookup },
      { key: "transfer_date", label: "Transfer date", kind: "date", required: true },
      { key: "status", label: "Status", kind: "select", options: warehouseDocumentStatuses },
      { key: "reference_code", label: "Reference code", kind: "text" },
      { key: "requested_by_user_id", label: "Requested by user", kind: "select", lookup: userLookup },
      { key: "confirmed_by_user_id", label: "Confirmed by user", kind: "select", lookup: userLookup },
      { key: "notes", label: "Notes", kind: "textarea" },
    ],
  },
  stock_transfer_lines: {
    title: "Stock transfer lines",
    apiPath: "/api/stock-transfer-lines",
    fields: [
      { key: "stock_transfer_document_id", label: "Stock transfer document ID", kind: "number", required: true },
      { key: "product_id", label: "Product", kind: "select", required: true, lookup: productLookup },
      { key: "from_position_id", label: "From position", kind: "select", required: true, lookup: warehousePositionLookup },
      { key: "to_position_id", label: "To position", kind: "select", required: true, lookup: warehousePositionLookup },
      { key: "quantity", label: "Quantity", kind: "number", required: true, step: "any", min: 0.000001 },
      { key: "unit_id", label: "Unit", kind: "select", required: true, lookup: unitLookup },
      { key: "line_notes", label: "Line notes", kind: "textarea" },
    ],
  },
  stock_reservations: {
    title: "Stock reservations",
    apiPath: "/api/stock-reservations",
    tableColumns: [
      { key: "product_id", label: "Product" },
      { key: "warehouse_id", label: "Warehouse" },
      { key: "position_id", label: "Position" },
      { key: "status", label: "Status", format: "status" },
      { key: "reserved_qty", label: "Reserved Qty" },
      { key: "reserved_from", label: "Reserved From", format: "datetime" },
      { key: "reserved_until", label: "Reserved Until", format: "datetime" },
    ],
    searchKeys: ["reservation_reason", "release_reason"],
    filters: [
      { key: "status", label: "Status", options: reservationStatuses },
    ],
    formSections: [
      { key: "item", label: "Item & Location" },
      { key: "context", label: "Context / Links" },
      { key: "lifecycle", label: "Lifecycle / Dates" },
      { key: "notes", label: "Notes" },
    ],
    fields: [
      { key: "product_id", label: "Product", kind: "select", required: true, lookup: productLookup, section: "item" },
      { key: "warehouse_id", label: "Warehouse", kind: "select", required: true, lookup: warehouseLookup, section: "item" },
      { key: "position_id", label: "Position", kind: "select", required: true, lookup: warehousePositionLookup, section: "item" },
      { key: "reserved_qty", label: "Reserved qty", kind: "number", required: true, step: "any", min: 0.000001, section: "item" },
      { key: "quote_line_id", label: "Quote line", kind: "select", lookup: quoteLineLookup, section: "context" },
      { key: "order_line_id", label: "Order line", kind: "select", lookup: orderLineLookup, section: "context" },
      { key: "configuration_variant_id", label: "Configuration variant", kind: "select", lookup: variantLookup, section: "context" },
      { key: "bom_line_id", label: "BOM line ID", kind: "number", section: "context" },
      { key: "status", label: "Status", kind: "select", options: reservationStatuses, section: "lifecycle" },
      { key: "reserved_from", label: "Reserved from", kind: "datetime-local", section: "lifecycle" },
      { key: "reserved_until", label: "Reserved until", kind: "datetime-local", section: "lifecycle" },
      { key: "created_by_user_id", label: "Created by user", kind: "select", lookup: userLookup, section: "lifecycle" },
      { key: "released_by_user_id", label: "Released by user", kind: "select", lookup: userLookup, section: "lifecycle" },
      { key: "reservation_reason", label: "Reservation reason", kind: "textarea", section: "notes" },
      { key: "release_reason", label: "Release reason", kind: "textarea", section: "notes" },
    ],
  },
} as const satisfies EntityConfigMap;

export const warehouseNavGroup: AdminNavGroup = {
  label: "Warehouse",
  href: "/admin/warehouse",
  items: [
    { href: "/admin/stock-reservations", label: "Stock Reservations" },
    { href: "/admin/stock-movements", label: "Stock Movements" },
    { href: "/admin/stock-balances", label: "Stock Balances" },
    { href: "/admin/purchase-receipts", label: "Purchase Receipts" },
    { href: "/admin/stock-transfer-documents", label: "Stock Transfer Documents" },
    { href: "/admin/inventory-counts", label: "Inventory Counts" },
    { href: "/admin/stock-adjustments", label: "Stock Adjustments" },
    { href: "/admin/stock-writeoffs", label: "Stock Writeoffs" },
    { href: "/admin/warehouses", label: "Warehouses" },
    { href: "/admin/warehouse-positions", label: "Warehouse Positions" },
    { href: "/admin/stock-movement-lines", label: "Stock Movement Lines" },
    { href: "/admin/purchase-receipt-lines", label: "Purchase Receipt Lines" },
    { href: "/admin/stock-adjustment-lines", label: "Stock Adjustment Lines" },
    { href: "/admin/stock-writeoff-lines", label: "Stock Writeoff Lines" },
    { href: "/admin/inventory-count-lines", label: "Inventory Count Lines" },
    { href: "/admin/stock-transfer-lines", label: "Stock Transfer Lines" },
  ],
};
