import {
  TABLE_BOM_CHANGE_LOGS,
  TABLE_BOM_LINES,
  TABLE_BRANCHES,
  TABLE_CALCULATION_RUNS,
  TABLE_CONFIGURATION_VISUALS,
  TABLE_DEPARTMENTS,
  TABLE_DOOR_CONFIGURATIONS,
  TABLE_DOOR_CONFIGURATION_INPUTS,
  TABLE_DOOR_CONFIGURATION_VARIANTS,
  TABLE_EMPLOYEES,
  TABLE_INSTALLATION_ASSIGNMENTS,
  TABLE_INSTALLATION_JOBS,
  TABLE_INSTALLATION_RESULTS,
  TABLE_INVENTORY_COUNT_LINES,
  TABLE_INVENTORY_COUNTS,
  TABLE_LOCATIONS,
  TABLE_ORDER_DISCOUNTS,
  TABLE_ORDER_LINES,
  TABLE_ORDERS,
  TABLE_PAYMENT_METHODS,
  TABLE_PAYMENTS,
  TABLE_PERMISSIONS,
  TABLE_PRODUCTS,
  TABLE_PRODUCT_ATTRIBUTES,
  TABLE_PRODUCT_BUNDLES,
  TABLE_PRODUCT_CATEGORIES,
  TABLE_PURCHASE_RECEIPT_LINES,
  TABLE_PURCHASE_RECEIPTS,
  TABLE_QUOTE_DISCOUNTS,
  TABLE_QUOTE_LINES,
  TABLE_QUOTES,
  TABLE_QUOTE_VERSIONS,
  TABLE_ROLES,
  TABLE_SPRING_CALCULATION_RESULTS,
  TABLE_STOCK_ADJUSTMENT_LINES,
  TABLE_STOCK_ADJUSTMENTS,
  TABLE_STOCK_BALANCES,
  TABLE_STOCK_MOVEMENT_LINES,
  TABLE_STOCK_MOVEMENTS,
  TABLE_STOCK_RESERVATIONS,
  TABLE_STOCK_TRANSFER_DOCUMENTS,
  TABLE_STOCK_TRANSFER_LINES,
  TABLE_STOCK_WRITEOFF_LINES,
  TABLE_STOCK_WRITEOFFS,
  TABLE_SUPPLIERS,
  TABLE_UNITS_OF_MEASURE,
  TABLE_USERS,
  TABLE_WAREHOUSES,
  TABLE_WAREHOUSE_POSITIONS,
} from "@one-technology/db";

type AllowedTable =
  | typeof TABLE_USERS
  | typeof TABLE_ROLES
  | typeof TABLE_PERMISSIONS
  | typeof TABLE_DEPARTMENTS
  | typeof TABLE_EMPLOYEES
  | typeof TABLE_BRANCHES
  | typeof TABLE_LOCATIONS
  | typeof TABLE_WAREHOUSES
  | typeof TABLE_WAREHOUSE_POSITIONS
  | typeof TABLE_PRODUCT_CATEGORIES
  | typeof TABLE_UNITS_OF_MEASURE
  | typeof TABLE_SUPPLIERS
  | typeof TABLE_PRODUCTS
  | typeof TABLE_PURCHASE_RECEIPTS
  | typeof TABLE_PURCHASE_RECEIPT_LINES
  | typeof TABLE_PRODUCT_ATTRIBUTES
  | typeof TABLE_PRODUCT_BUNDLES
  | typeof TABLE_STOCK_ADJUSTMENTS
  | typeof TABLE_STOCK_ADJUSTMENT_LINES
  | typeof TABLE_STOCK_BALANCES
  | typeof TABLE_STOCK_WRITEOFFS
  | typeof TABLE_STOCK_WRITEOFF_LINES
  | typeof TABLE_INVENTORY_COUNTS
  | typeof TABLE_INVENTORY_COUNT_LINES
  | typeof TABLE_STOCK_TRANSFER_DOCUMENTS
  | typeof TABLE_STOCK_TRANSFER_LINES
  | typeof TABLE_STOCK_MOVEMENTS
  | typeof TABLE_STOCK_MOVEMENT_LINES
  | typeof TABLE_STOCK_RESERVATIONS
  | typeof TABLE_DOOR_CONFIGURATIONS
  | typeof TABLE_DOOR_CONFIGURATION_VARIANTS
  | typeof TABLE_DOOR_CONFIGURATION_INPUTS
  | typeof TABLE_CALCULATION_RUNS
  | typeof TABLE_SPRING_CALCULATION_RESULTS
  | typeof TABLE_BOM_LINES
  | typeof TABLE_BOM_CHANGE_LOGS
  | typeof TABLE_CONFIGURATION_VISUALS
  | typeof TABLE_QUOTES
  | typeof TABLE_QUOTE_VERSIONS
  | typeof TABLE_QUOTE_LINES
  | typeof TABLE_QUOTE_DISCOUNTS
  | typeof TABLE_ORDERS
  | typeof TABLE_ORDER_LINES
  | typeof TABLE_ORDER_DISCOUNTS
  | typeof TABLE_PAYMENT_METHODS
  | typeof TABLE_PAYMENTS
  | typeof TABLE_INSTALLATION_JOBS
  | typeof TABLE_INSTALLATION_ASSIGNMENTS
  | typeof TABLE_INSTALLATION_RESULTS;

export async function rowExists(
  db: D1Database,
  table: AllowedTable,
  id: number
): Promise<boolean> {
  const row = await db
    .prepare(`SELECT 1 AS ok FROM ${table} WHERE id = ? LIMIT 1`)
    .bind(id)
    .first<{ ok: number }>();
  return !!row;
}
