import {
  TABLE_BRANCHES,
  TABLE_DEPARTMENTS,
  TABLE_LOCATIONS,
  TABLE_PERMISSIONS,
  TABLE_PRODUCT_ATTRIBUTES,
  TABLE_PRODUCT_BUNDLES,
  TABLE_PRODUCT_CATEGORIES,
  TABLE_PRODUCTS,
  TABLE_PURCHASE_RECEIPT_LINES,
  TABLE_PURCHASE_RECEIPTS,
  TABLE_ROLES,
  TABLE_STOCK_BALANCES,
  TABLE_STOCK_ADJUSTMENT_LINES,
  TABLE_STOCK_ADJUSTMENTS,
  TABLE_STOCK_TRANSFER_DOCUMENTS,
  TABLE_STOCK_TRANSFER_LINES,
  TABLE_STOCK_MOVEMENT_LINES,
  TABLE_STOCK_MOVEMENTS,
  TABLE_STOCK_WRITEOFF_LINES,
  TABLE_STOCK_WRITEOFFS,
  TABLE_SUPPLIERS,
  TABLE_UNITS_OF_MEASURE,
  TABLE_USERS,
  TABLE_WAREHOUSES,
  TABLE_WAREHOUSE_POSITIONS,
  TABLE_INVENTORY_COUNT_LINES,
  TABLE_INVENTORY_COUNTS,
} from "@one-technology/db";

type AllowedTable =
  | typeof TABLE_USERS
  | typeof TABLE_ROLES
  | typeof TABLE_PERMISSIONS
  | typeof TABLE_DEPARTMENTS
  | typeof TABLE_BRANCHES
  | typeof TABLE_LOCATIONS
  | typeof TABLE_WAREHOUSES
  | typeof TABLE_WAREHOUSE_POSITIONS
  | typeof TABLE_PRODUCT_CATEGORIES
  | typeof TABLE_UNITS_OF_MEASURE
  | typeof TABLE_SUPPLIERS
  | typeof TABLE_PRODUCTS
  | typeof TABLE_PURCHASE_RECEIPTS
  | typeof TABLE_PURCHASE_RECEIPT_LINES
  | typeof TABLE_PRODUCT_ATTRIBUTES
  | typeof TABLE_PRODUCT_BUNDLES
  | typeof TABLE_STOCK_ADJUSTMENTS
  | typeof TABLE_STOCK_ADJUSTMENT_LINES
  | typeof TABLE_STOCK_BALANCES
  | typeof TABLE_STOCK_WRITEOFFS
  | typeof TABLE_STOCK_WRITEOFF_LINES
  | typeof TABLE_INVENTORY_COUNTS
  | typeof TABLE_INVENTORY_COUNT_LINES
  | typeof TABLE_STOCK_TRANSFER_DOCUMENTS
  | typeof TABLE_STOCK_TRANSFER_LINES
  | typeof TABLE_STOCK_MOVEMENTS
  | typeof TABLE_STOCK_MOVEMENT_LINES;

export async function rowExists(
  db: D1Database,
  table: AllowedTable,
  id: number
): Promise<boolean> {
  const row = await db
    .prepare(`SELECT 1 AS ok FROM ${table} WHERE id = ? LIMIT 1`)
    .bind(id)
    .first<{ ok: number }>();
  return !!row;
}
